
scan_specific_scalars = [
    'time.yr',
    'time.mo',
    'time.dy',
    'time.hr',
    'time.mt',
    'time.sc',
    'time.us',
    'intt.sc',
    'intt.us',
    'radar.revision.major',
    'radar.revision.minor',
    'origin.code',
    'origin.time',
    'origin.command',
    'cp',
    'stid',
    'txpow',
    'nave',
    'atten',
    'lagfr',
    'smsep',
    'ercod',
    'stat.agc',
    'stat.lopwr',
    'noise.search',
    'noise.mean',
    'channel',
    'scan',
    'offset',
    'rxrise',
    'txpl',
    'mpinc',
    'mppul',
    'mplgs',
    'mplgexs',
    'ifmode',
    'nrang',
    'frang',
    'rsep',
    'xcf',
    'tfreq',
    'mxpwr',
    'lvmax',
    'combf',
    'algorithm',
    'fitacf.revision.major',
    'fitacf.revision.minor',
    'noise.sky',
    'noise.lag0',
    'noise.vel',
    'tdiff'
]

record_specific_scalars = [
    'bmnum',
    'bmazm'
]

scan_specific_vectors = [
    'ptab',
    'ltab',
]

record_specific_vectors = [
    'pwr0',
    'slist',
    'nlag',
    'qflg',
    'gflg',
    'p_l',
    'p_l_e',
    'p_s',
    'p_s_e',
    'v',
    'v_e',
    'w_l',
    'w_l_e',
    'w_s',
    'w_s_e',
    'sd_l',
    'sd_s',
    'sd_phi',
    'x_qflg',
    'x_gflg',
    'x_p_l',
    'x_p_l_e',
    'x_p_s',
    'x_p_s_e',
    'x_v',
    'x_v_e',
    'x_w_l',
    'x_w_l_e',
    'x_w_s',
    'x_w_s_e',
    'phi0',
    'phi0_e',
    'elv',
    'elv_fitted',
    'elv_error',
    'elv_low',
    'elv_high',
    'x_sd_l',
    'x_sd_s',
    'x_sd_phi'
]

keys = scan_specific_scalars + scan_specific_vectors + record_specific_scalars + record_specific_vectors

